#!/usr/bin/env bash
# Assembles one project's bootable disk: base rootfs + its built tree + an init
# that starts it, written out as an ext4 image.
#
#   assemble.sh <id> <runtime> <source-dir> <start-command...>
#
# Built with `mke2fs -d`, which populates a filesystem image from a directory
# **without mounting it**. The obvious alternative -- losetup plus a real mount
# -- needs CAP_SYS_ADMIN in the host mount namespace, on the one box where
# handing that out is least appealing. This needs neither.
#
# The tree arriving in <source-dir> is expected to have its dependencies already
# installed. Installing them is a separate step and deliberately not done here:
# `npm install` runs arbitrary postinstall code, and the right place for that is
# a throwaway microVM with network, not this script running on the host.
set -euo pipefail

REPO_RUNTIME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../runtime" && pwd)"
NODE="${NODE:-/opt/node22/bin/node}"
FC_DIR="${FC_DIR:-/opt/firecracker}"
APPS_DIR="${APPS_DIR:-/opt/boxcode-apps}"

id="${1:?usage: assemble.sh <id> <runtime> <source-dir> <start-command...>}"
runtime="${2:?runtime: node or python}"
src="${3:?source directory}"
shift 3
[ "$#" -gt 0 ] || { echo "a start command is required" >&2; exit 2; }

# Validate the id here as well as in the Node module. This script can be run by
# hand, and every path below is built by concatenation.
case "$id" in
    *[!a-z2-9]* | "" ) echo "invalid project id: $id" >&2; exit 2 ;;
esac
[ "${#id}" -ge 4 ] && [ "${#id}" -le 16 ] || { echo "invalid project id length: $id" >&2; exit 2; }

[ -d "$src" ] || { echo "no such source directory: $src" >&2; exit 2; }

base_name="$("$NODE" -e "
  import('file://$REPO_RUNTIME/rootfs.mjs')
    .then(m => console.log(m.baseFor(process.argv[1])))
    .catch(e => { console.error(e.message); process.exit(1); });
" "$runtime")"
base="$FC_DIR/base/$base_name"
[ -d "$base" ] || { echo "base rootfs missing: $base -- run rootfs/build-base.sh" >&2; exit 1; }

dir="$APPS_DIR/$id"
staging="$dir/staging"
image="$dir/rootfs.ext4"

echo "== $id: sizing =="
tree_bytes=$(du -sb "$src" | cut -f1)
base_mib=$(( $(du -sm "$base" | cut -f1) ))
if [ "$("$NODE" -e "
  import('file://$REPO_RUNTIME/rootfs.mjs').then(m =>
    console.log(m.tooLarge(Number(process.argv[1]), Number(process.argv[2]))));
" "$tree_bytes" "$base_mib")" = "true" ]; then
    echo "project $id is too large to fit the image ceiling." >&2
    echo "tree is $((tree_bytes / 1024 / 1024)) MiB on a ${base_mib} MiB base." >&2
    # Said here, plainly, rather than letting it surface as a cryptic mke2fs
    # failure part-way through writing the filesystem.
    exit 1
fi
size_mib=$("$NODE" -e "
  import('file://$REPO_RUNTIME/rootfs.mjs').then(m =>
    console.log(m.imageSizeMib(Number(process.argv[1]), Number(process.argv[2]))));
" "$tree_bytes" "$base_mib")
echo "   tree $((tree_bytes / 1024 / 1024)) MiB + base ${base_mib} MiB -> image ${size_mib} MiB"

echo "== $id: staging =="
sudo rm -rf "$staging"
sudo mkdir -p "$staging"
# --reflink=auto makes this near-free on xfs, which is what AL2023 uses, and
# falls back to a real copy anywhere else rather than failing.
sudo cp -a --reflink=auto "$base/." "$staging/"
sudo rm -rf "$staging/app"
sudo mkdir -p "$staging/app"
sudo cp -a "$src/." "$staging/app/"
sudo chown -R 1000:1000 "$staging/app"

echo "== $id: init =="
# Generated by the same module the tests cover, so the shell never builds this
# text itself -- start command words and environment values are attacker-
# influenced and the quoting rules are the thing people get subtly wrong.
"$NODE" -e "
  import('file://$REPO_RUNTIME/rootfs.mjs').then(m => {
    process.stdout.write(m.renderInit({
      startCommand: process.argv.slice(1),
      env: JSON.parse(process.env.BOXCODE_APP_ENV || '{}'),
    }));
  });
" "$@" | sudo tee "$staging/sbin/init" >/dev/null
sudo chmod 0755 "$staging/sbin/init"

echo "== $id: build-init =="
# The same image carries both inits. The build boots it with
# init=/sbin/build-init on the kernel command line, installs dependencies into
# /app, and powers off; the app then boots the very same disk with the default
# init and its node_modules are simply there. Nothing is copied out, nothing is
# mounted, and there is no second block device.
lockfile=false
manifest=null
case "$runtime" in
    node)
        [ -f "$src/package-lock.json" ] && lockfile=true
        ;;
    python)
        for m in requirements.txt pyproject.toml setup.py; do
            if [ -f "$src/$m" ]; then manifest="\"$m\""; break; fi
        done
        ;;
esac
"$NODE" -e "
  import('file://$REPO_RUNTIME/build.mjs').then(m => {
    const cmds = m.installCommands(process.argv[1], {
      lockfile: process.argv[2] === 'true',
      manifest: JSON.parse(process.argv[3]),
    });
    process.stdout.write(m.renderBuildInit({
      commands: cmds,
      env: JSON.parse(process.env.BOXCODE_BUILD_ENV || '{}'),
    }));
  });
" "$runtime" "$lockfile" "$manifest" | sudo tee "$staging/sbin/build-init" >/dev/null
sudo chmod 0755 "$staging/sbin/build-init"

echo "== $id: mke2fs =="
sudo rm -f "$image"
mapfile -t args < <("$NODE" -e "
  import('file://$REPO_RUNTIME/rootfs.mjs').then(m =>
    console.log(m.mke2fsArgs({
      imagePath: process.argv[1],
      stagingDir: process.argv[2],
      sizeMib: Number(process.argv[3]),
    }).join('\n')));
" "$image" "$staging" "$size_mib")
sudo mke2fs "${args[@]}" >/dev/null

# Staging is several hundred megabytes per project and its only purpose was to
# be copied into the image. Ten of these left behind is most of the disk.
sudo rm -rf "$staging"

echo "== $id: done =="
ls -lh "$image"
