// The systemd unit a hosted app runs under, which is also the whole of its
// sandbox.
//
// Containers were doing this job. Without them the isolation has to come from
// the kernel directly, and systemd exposes the same primitives Docker was
// driving -- cgroup limits, mount namespaces, seccomp, capability bounding,
// and BPF egress filtering. So this is not a weaker sandbox for being simpler;
// it is the same mechanisms with less machinery in front of them.
//
// What it does NOT replace is gVisor. A container escape and a systemd escape
// both land on the same shared kernel, and there is no user-space kernel in
// front of it any more. That is the cost of the simplification and it should be
// stated plainly rather than papered over.
//
// This is the file where deleting one line silently removes a security
// property and nothing afterwards looks wrong, so every directive below has a
// test asserting it is present.

export const ID_RE = /^[a-z2-9]{4,16}$/;

/// Matches capacity.mjs. Enforced here by MemoryMax, and the cgroup is the same
/// one Docker was setting -- systemd is not a softer ceiling.
export const APP_MEMORY_MB = 256;
export const APP_CPU_PERCENT = 25;
export const APP_TASKS_MAX = 128;

function must(id) {
  if (typeof id !== "string" || !ID_RE.test(id)) {
    throw new Error(`refusing to build a unit for invalid id ${JSON.stringify(id)}`);
  }
  return id;
}

export function unitName(id) {
  return `boxcode-app-${must(id)}`;
}

/// One Unix user per app, so the filesystem itself separates tenants. Without
/// this every app runs as the same user and can read every other app's code,
/// its .env, and its database password -- which is exactly what a shared
/// process manager like pm2 would have given us.
export function userName(id) {
  return `bcapp-${must(id)}`;
}

export function appRoot(id, base = "/opt/boxcode-apps") {
  return `${base}/${must(id)}`;
}

/// systemd reads unit files line by line, so a newline inside a value is not a
/// broken string -- it is a new directive. An app's DATABASE_URL containing
/// "\nExecStartPre=/bin/sh -c ..." would be executed as root at start. Values
/// reaching here are attacker-influenced, so anything that could end a line is
/// refused outright rather than escaped.
function safeEnvValue(key, value) {
  const v = String(value);
  if (/[\n\r]/.test(v)) {
    throw new Error(`refusing environment value for ${key}: contains a newline, which would inject a unit directive`);
  }
  if (v.includes('"') || v.includes("\\")) {
    throw new Error(`refusing environment value for ${key}: contains a quote or backslash`);
  }
  return v;
}

/// The unit file text.
export function renderUnit({ id, port, execStart, env = {}, base = "/opt/boxcode-apps" }) {
  const app = appRoot(id, base);
  const user = userName(id);

  if (!Number.isInteger(port) || port < 1024 || port > 65535) {
    throw new Error(`refusing to run app ${id} on invalid port ${port}`);
  }
  if (typeof execStart !== "string" || execStart.trim() === "" || /[\n\r]/.test(execStart)) {
    throw new Error(`refusing invalid ExecStart for ${id}`);
  }

  const envLines = Object.entries(env).map(([k, v]) => {
    if (!/^[A-Z_][A-Z0-9_]*$/.test(k)) {
      throw new Error(`refusing environment variable with invalid name ${JSON.stringify(k)}`);
    }
    return `Environment="${k}=${safeEnvValue(k, v)}"`;
  });

  return `# Generated by the boxcode hosting control-plane. Do not edit by hand:
# the next deploy of ${id} overwrites this file.
[Unit]
Description=boxcode hosted app ${id}
After=network.target postgresql.service
# The app is useless without its database and should not flap trying.
Requires=postgresql.service
# These belong here, not under the service section. Put there, systemd logs
# "Unknown key ... ignoring" and starts the unit anyway, so the crash-loop
# ceiling is silently absent -- caught by systemd-analyze verify, not by
# reading it. (Avoid writing a section name in a comment: it reads as a header
# to anything scanning the file, this project's own tests included.)
StartLimitIntervalSec=300
StartLimitBurst=10

[Service]
Type=simple
User=${user}
Group=bcapp
WorkingDirectory=${app}/app
ExecStart=${execStart}
Environment="PORT=${port}"
Environment="NODE_ENV=production"
${envLines.join("\n")}

# Restart, but not forever: an app crash-looping on a bad config should stop
# and be visible, not consume a CPU quota for two days pretending to work.
Restart=always
RestartSec=2

# ---- resource ceilings ------------------------------------------------
# The same cgroup v2 knobs Docker was setting. MemorySwapMax=0 matters as much
# as MemoryMax: without it a leaking app swaps instead of dying and drags every
# other app down through the disk.
MemoryMax=${APP_MEMORY_MB}M
MemorySwapMax=0
CPUQuota=${APP_CPU_PERCENT}%
TasksMax=${APP_TASKS_MAX}

# ---- privilege --------------------------------------------------------
NoNewPrivileges=yes
CapabilityBoundingSet=
AmbientCapabilities=
RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
# One ~ prefixes the whole list. Written per entry (~@privileged ~@mount ...)
# only the first is a denial; the rest are parsed as literal syscall names,
# fail to resolve, and are dropped with a log line nobody reads.
#
# @resources is deliberately not denied: it covers setrlimit, nice and the
# sched_* calls, which Node's thread pool and CPython both use legitimately.
# @system-service already excludes the dangerous parts of it.
SystemCallFilter=~@privileged @obsolete @mount @debug @swap @reboot @module @raw-io
# MemoryDenyWriteExecute is deliberately NOT set. It is normally a good
# hardening default, and it breaks every runtime this platform exists to host:
# V8 and CPython both map writable-executable pages for JIT and ctypes. Setting
# it would refuse Node and most Python apps at startup.

# ---- what it can see --------------------------------------------------
# Anything the app writes is readable only by itself. Without this, files land
# world-readable and the per-user separation below leaks through the one place
# every tenant can still see: its own data directory's permissions.
UMask=0077
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
# The app cannot see any process but its own -- so it cannot read another
# tenant's command line, and command lines are where secrets get left.
ProtectProc=invisible
ProcSubset=pid

# An empty tmpfs over the apps directory, then only this app's own paths
# mounted back into it. In this unit's mount namespace the other tenants do
# not exist at all, rather than existing and being unreadable.
TemporaryFileSystem=${base}:ro
BindReadOnlyPaths=${app}/app
BindPaths=${app}/data

# ---- network ----------------------------------------------------------
# The highest-value control, and the whole of it. Loopback only: nginx can
# reach the app and the app can reach Postgres on 127.0.0.1, and there is no
# route anywhere else. No mining pool, no C2, no spam relay, no exfiltration.
#
# Enforced by a BPF cgroup filter, so it holds for every process the app
# spawns, not just the one systemd started.
IPAddressDeny=any
IPAddressAllow=localhost
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX

# ---- logs -------------------------------------------------------------
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${unitName(id)}

[Install]
WantedBy=multi-user.target
`;
}

/// nginx location block routing /api/<id>/ to this app.
export function renderNginxRoute(id, port) {
  must(id);
  if (!Number.isInteger(port) || port < 1024 || port > 65535) {
    throw new Error(`refusing to route app ${id} to invalid port ${port}`);
  }
  return `# Generated for ${id}. Regenerated on every deploy.
location ^~ /api/${id}/ {
    proxy_pass http://127.0.0.1:${port}/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    # WebSockets, which is one of the things Lambda could not do at all.
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_read_timeout 60s;
}
`;
}
